apiVersion: apps/v1
kind: Deployment
metadata:
  name: neitosden-react
  namespace: neitosden-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neitosden-react
  template:
    metadata:
      labels:
        app: neitosden-react
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: neitosden-react
        image: ghcr.io/neito-s-den/react-web/app:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5173
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"