services:
  web:
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.dev
    ports:
      - "5173:5173" # Map Vite's development port
    volumes:
      - ../front:/app # Mount the project directory to the container's /app folder
    environment:
      - NODE_ENV=development
    # command: sleep infinity
    stdin_open: true # Enable interaction
    tty: true # Enable TTY
