name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted # Run this job on your self-hosted runner
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full git history is fetched, including tags

      - name: Set GitHub user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"

      # Step to pull the latest Docker image matching the tag and deploy with Helm
      - name: Deploy to Kubernetes using Helm
        run: |
          # Check if the tag was correctly fetched
          TAG=$(git describe --tags --abbrev=0)
          echo "Deploying version $TAG"

          # Perform Helm upgrade (or install if it doesn't exist)
          helm upgrade --install betterpi ./ops/helm \
            --namespace neitosden-react \
            --set imagesConfiguration.global.tag="$TAG"

      # Optional: Verify the deployment status
      - name: Check Deployment Status
        run: |
          helm status -n neitosden-react betterpi
